### ISSUE TITLE
[feat/modularization] 기초 모듈 생성

### ISSUE THREAD

**Issue by hanseul-Choi** [hanseul-Choi/practice-kakao-search#2]
## Description
기초 모듈 생성 작업 수행하기

## To-do
- [ ] core/model module 생성
- [ ] core/data module 생성
- [ ] core/domain module 생성
- [ ] core/network module 생성
- [ ] feature/search module 생성
- [ ] feature/favorite module 생성
